"use client"
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Notification from '@/components/Notification'
import Navbar from '@/components/Navbar'
import Fotter from '@/components/Fotter'
import 'tailwindcss/tailwind.css'; 
import 'font-awesome/css/font-awesome.min.css';
import dbConnect from '@/lib/dbConnect'
import { Providers } from './redux/provider'
import CallTheState from './redux/CallTheState'


// console.log("connecting ... ")
// dbConnect();
const inter = Inter({ subsets: ['latin'] })
// export const metadata: Metadata = {
//   title: 'Restaurant',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="Restaurant app" />
          <link rel="icon" href="./logo.png" />
          <title>Restaurant</title>
        </head>
      <body className={inter.className}>
        <Providers>
          <CallTheState>
            <Notification />
            <Navbar />
            {children}
          </CallTheState>
        </Providers>
        <Fotter />
      </body>
    </html >
  )
}
