
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Notification from '@/components/Notification'
import Navbar from '@/components/Navbar'
import Fotter from '@/components/Fotter'
import 'tailwindcss/tailwind.css'; 
import 'font-awesome/css/font-awesome.min.css';
import dbConnect from '@/lib/dbConnect'
import { Providers } from './redux/provider'
import CallTheState from './redux/CallTheState'

console.log("connecting ... ")
dbConnect();
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Restaurant',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        {/* <CallTheState/> */}
        <Notification />
        <Navbar />

           {children}
        </Providers>
        <Fotter />
      </body>
    </html >
  )
}
